sr_scara_hx:
  sr_scara_hx_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3

    gains:
      joint1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint2: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint3:  {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

